name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Jobo hello-world patikrinimas
  hello-world:
    runs-on: ubuntu-latest

    steps:
      # 1. Atsiunčia actiona iš github
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Įdiegia Node.js aplinką
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      # 3. Linting etapas
      - name: Run ESLint
        run: |
          npm install
          npx eslint index.js    

      # 4. Paleidžia Hello World programą
      - name: Run Hello World
        run: |
          echo "Hello from CI/CD!"
          node index.js
