name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies and run ESLint
      - name: Run ESLint
        run: |
          npm install
          npx eslint index.js

      # 4. Run Hello World program
      - name: Run Hello World
        run: |
          echo "Hello from CI/CD!"
          node index.js
