name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Debug ESLint (optional step for troubleshooting)
      - name: Debug ESLint Binary
        run: |
          ls -l ./node_modules/.bin/
          ./node_modules/.bin/eslint --version

      # 5. Run ESLint
      - name: Run ESLint
        run: npx eslint index.js

      # 6. Run Hello World
      - name: Run Hello World
        run: |
          echo "Hello from CI/CD!"
          node index.js
